[package]
name = "lua53-sys"
version = "0.1.0"
authors = ["Mathew Velasquez <mathewvq@gmail.com>"]
description = "Bindings for Lua 5.3"
build = "build.rs"
links = "lua"
license = "MIT"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
